---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: admin_user_name
      prompt: AD Domain admin account (or leave blank to skip)
    - name: admin_password
      prompt: AD Domain admin account password (or leave blank to skip)
  vars_files:
    - "{{ path_to_vars_file if path_to_vars_file is defined else 'vars/globals.yml' }}"
  vars:
    input: &input
      hostname: '{{ netapp_hostname }}'
      username: '{{ netapp_username }}'
      password: '{{ netapp_password }}'
      https: true
      validate_certs: false
  tasks:
    - name: Get ONTAP facts
      na_ontap_gather_facts:
        state: info
        <<: *input
    - import_role:
        name: na_ontap_cluster_config
      vars:
        <<: *input
    - import_role:
        name: na_ontap_vserver_create
      vars:
        <<: *input
    - import_role:
        name: na_ontap_nas_create
      vars:
        <<: *input
    - import_role:
        name: na_ontap_san_create
      vars:
        <<: *input
